### ISSUE TITLE
patch 0.0.7.0 violates PVP

### ISSUE THREAD

**Issue by phadej** [reflex-frp/patch#49]
The change of defining own `Additive` class to doing `type Additive = Commutative` is a **breaking change**.

Please pay attention to versioning. See https://pvp.haskell.org/

**Comment by Ericson2314** [comment]
Can you write a program depending on `patch` which breaks because of this change?

**Comment by phadej** [comment]
reflex-0.8.2.0 is an example.

**Comment by Ericson2314** [comment]
If the issue is `instance Alias Arg` doesn't work, fair enough, but we should fix the language so it does rather than give up on equational reasoning.

Anyways is this an actionable issue? The releases are cut, you did a reflex-0.8.2.0 revision so the new patch version is no longer selected. Is there something else you would like us to do?

**Comment by phadej** [comment]
> Anyways is this an actionable issue? The releases are cut, you did a reflex-0.8.2.0 revision so the new patch version is no longer selected. Is there something else you would like us to do?

Blacklist `patch-0.0.7` with `base <0` revision. Release `patch-0.1`. Or even acknowledge the problem and be more careful in the future.

**Comment by phadej** [comment]
E.g. `Commutative` leaks also into `reflex`s` public API: https://hackage.haskell.org/package/reflex-0.8.2.1/docs/Reflex-Query-Class.html#t:MonadQuery, so technically also `relfex` violated PVP.

(I don't use `MonadQuery` so my apps didn't broke, but they could).

**Comment by Ericson2314** [comment]
I'll look into the new version and old version blacklisting. Please lead with what you want to be done in the future rather then merely chiding the authors.
